local repo = require('whiteboard-nvim.repo')

describe('whiteboard-nvim.repo', function()
  describe('relative_path', function()
    it('strips repo root prefix', function()
      local rel = repo.relative_path('/home/user/project', '/home/user/project/lua/foo.lua')
      assert.are.equal('lua/foo.lua', rel)
    end)

    it('handles trailing slash on root', function()
      local rel = repo.relative_path('/home/user/project/', '/home/user/project/lua/foo.lua')
      assert.are.equal('lua/foo.lua', rel)
    end)

    it('returns the original path when not under root', function()
      local rel = repo.relative_path('/other/project', '/home/user/project/foo.lua')
      assert.are.equal('/home/user/project/foo.lua', rel)
    end)

    it('normalizes backslashes to forward slashes', function()
      local rel = repo.relative_path('C:/Users/Travi/project', 'C:\\Users\\Travi\\project\\lua\\foo.lua')
      assert.are.equal('lua/foo.lua', rel)
    end)
  end)

  describe('board_path', function()
    it('returns a .json path inside the nvim data directory', function()
      local p = repo.board_path('/home/user/project')
      assert.is_truthy(p:match('whiteboard[/\\]boards[/\\][a-f0-9]+%.json$'))
    end)

    it('returns different paths for different roots', function()
      local a = repo.board_path('/project/a')
      local b = repo.board_path('/project/b')
      assert.are_not.equal(a, b)
    end)

    it('returns the same path for the same root', function()
      local a = repo.board_path('/project/same')
      local b = repo.board_path('/project/same')
      assert.are.equal(a, b)
    end)
  end)
end)
